name: Run tests on Znuny and update package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      package:
        required: false
        type: string

jobs:
  Run:
    runs-on: ubuntu-latest
    container: debian:10-slim

    services:
      chrome:
        image: selenium/standalone-chrome:3.141.59-oxygen
        options: --shm-size="2g"
        volumes:
          - ${{ github.workspace }}:/opt/otrs

      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: "otrs"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_PASSWORD: "secret"
          MYSQL_DATABASE: "otrs"

    steps:
      - name: Install dependencies
        run: |
          uname -a
          apt-get update
          apt-get upgrade -y
          apt-get install -y libapache2-mod-perl2 libdbd-mysql-perl \
            libtimedate-perl libnet-dns-perl libnet-ldap-perl \
            libio-socket-ssl-perl libpdf-api2-perl libdbd-mysql-perl \
            libsoap-lite-perl libtext-csv-xs-perl libjson-xs-perl \
            libapache-dbi-perl libxml-libxml-perl libxml-libxslt-perl libspreadsheet-xlsx-perl \
            libyaml-perl libarchive-zip-perl  libcrypt-eksblowfish-perl \
            libencode-hanextra-perl libmail-imapclient-perl libtemplate-perl \
            libdatetime-perl libmoo-perl apache2 mariadb-client gnupg2 liblocale-po-perl \
            libhash-merge-perl libxml2-utils gnupg2 cpanminus make gcc git npm gettext \
            rsync

      - name: Check out Znuny branch rel-${{ inputs.version }}
        uses: actions/checkout@v3
        with:
          repository: Znuny/Znuny
          ref: rel-${{ inputs.version }}

      - name: Check out current repository
        uses: actions/checkout@v3
        with:
          path: mxcModule

      - name: Check out scripts
        uses: actions/checkout@v3
        with:
          path: mxcScripts
          repository: maxence-de/github-mxc-WorkflowScripts
          token: ${{ secrets.CHECKOUTTOKEN }}
          
      - name: Run script
        run: |
          chmod 777 mxcScripts/run.sh
          mxcScripts/run.sh
        env:
          MYSQL_USER: "otrs"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_PASSWORD: "secret"
          MYSQL_DATABASE: "otrs"
          CHECKOUTTOKEN: ${{ secrets.CHECKOUTTOKEN }}
          VERSION: ${{ inputs.version }}
          PACKAGE: ${{ inputs.package }}
          
      - name: Archive screenshots from selenium
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Download all selenium screenshots
          retention-days: 3
          path: /opt/otrs/var/httpd/htdocs/SeleniumScreenshots/*.png
          if-no-files-found: ignore

      - name: Create pull request
        if: inputs.package == ''
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CHECKOUTTOKEN }}
          branch: update-rel_${{ inputs.version }}
          path: mxcModule
          title: 'Auto-generated update to Znuny ${{ inputs.version }}'
          body: |
            - Updated sopm
            - Created opm
            - Testes successfully on Znuny ${{ inputs.version }}

